### PR TITLE
Fix url for getting trustchain blocks for a specific user

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by qstokkink** [comment]
@xoriole your sonar cloud seems a little dead.

**Comment by xoriole** [comment]
@qstokkink seems like a permission issue. I'll fix that.

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by qstokkink** [comment]
@xoriole are you able to fix the sonar cloud thing or should we disable it?

**Comment by xoriole** [comment]
Sonar cloud check is working fine but there seems to be an issue with post-processing of the results in Jenkins. I'll enable the test once that is fixed, for now, let's disable it.

**Comment by qstokkink** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
Sonar cloud issue is fixed

Screenshot 2019-12-05 at 12 44 22

**Comment by qstokkink** [comment]
👍 I'll merge this PR now then.

**Pull request merged**
