### PR TITLE
Added serialization of lists of ints and booleans

### PR DESCRIPTION
**Pull request by bacox**
Hi all,

In my own code, support for serialization of native `ints` and `bool` came in handy. This might also be beneficial to this project.

This PR:

 - Adds serialization of dataclasses with attributes that are lists of native `ints` and `bools`.
 - Updated the unit tests to test dataclasses with `List[int]` and `List[bool]`

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
🤔 time to port validate_documentation to GitHub Actions. I can't seem to fix it on Jenkins.

**Review by egbertbouman — APPROVED** [review]

**Pull request merged**
