### PR TITLE
Fix dictionary changed size errors

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by qstokkink** [comment]
Is this only an issue on the master branch?

**Comment by egbertbouman** [comment]
@qstokkink Starting from Tribler 7.5, we no longer have a separate thread for making calls to the tunnel community, so I figured it's no longer needed.

**Comment by qstokkink** [comment]
I was thinking the REST API would cause issues, but I guess that also runs on the asyncio event loop. Should be good then 👍

**Comment by ichorid** [comment]
@egbertbouman, does it fix #4955 ?

**Comment by egbertbouman** [comment]
@ichorid Yes, it does.

**Pull request merged**
