### PR TITLE
Added apikey/TLS support to REST API server

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
@egbertbouman is this ready for review?

**Comment by egbertbouman** [comment]
@qstokkink It still needed a rebase after the previous merge. It's ready now.

It looks like the mac gets stuck sometimes during testing. I've seen this before a few days ago, and I hoped that my deadlock fix would solve it, but it looks like it's still there.

**Comment by qstokkink** [comment]
I fixed that in #772. It's a test in the old Attestation REST tests that is stuck on a while loop.

**Comment by qstokkink** [comment]
retest this please

**Pull request merged**
