### PR TITLE
Removed unnecessary ord calls

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/py-ipv8/issues/841.

### CODE REVIEW

**Comment by qstokkink** [comment]
Would you also be willing to fixup the remainder of `M2CryptoPK.verify`? It seems to be a bit.. broken.

**Comment by egbertbouman** [comment]
@qstokkink Sure, I'll take a look.

**Comment by qstokkink** [comment]
Thanks 👍. Specifically the `str` (`"\x00"`) + `bytes` object concatenations don't seem like they could possibly be correct.

**Comment by egbertbouman** [comment]
It's fixed now and I've added some unit tests to test signing/verifying.

I did notice that even though `M2CryptoSK` inherits from `M2CryptoPK` and therefore has a `verify` method, it does not work. You first have to get the `M2CryptoPK` by calling `pub()`, and then it does work. `LibNaCLSK` doesn't suffer from this.

**Comment by qstokkink** [comment]
> I did notice that even though M2CryptoSK inherits from M2CryptoPK and therefore has a verify method, it does not work. You first have to get the M2CryptoPK by calling pub(), and then it does work. LibNaCLSK doesn't suffer from this.

I just checked this out.. might have something to do with them not calling their `super(...).__init__`? We'll have to look at it, but let's not include that in this PR.

**Comment by qstokkink** [comment]
Follow-up: the `verify` issue has nothing to do with `super(...).__init__` apparently.

**Comment by qstokkink** [comment]
..and everything with the `try .. except` hiding the error 😃 I'll make a fix for this.

**Pull request merged**
