### PR TITLE
Fixed spelling and grammar instance in index.rst

### PR DESCRIPTION
**Pull request by qstokkink**
This PR:

 - Adds a fallback to the `"."` directory if `run_all_tests.py` is run from the `""` directory.
 - Fixes spelling and grammar instance in index.rst
 - Fixes the validation matrix still not using the PR head (this time using [this](https://github.com/actions/checkout/pull/1248/files) solution).
 
 This PR is mainly to test the recent validation Action fixes.

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
😕 it's still pulling the latest commit on `master` instead of the PR head:

```
 "C:\Program Files\Git\bin\git.exe" log -1 --format='%H'
'0f98cc5cbb95a794ae62f8767ebce036270532ee'
```

**Comment by qstokkink** [comment]
validate

**Review by egbertbouman — APPROVED** [review]

**Pull request merged**
