### PR TITLE
Added ruff configuration file

### LINKED ISSUE #1155: Investigate `ruff` as a replacement linter for `flake8` and `pylint`
Our current PR linters are Flake8 and Pylint. They take (depending on the size of the PR) in the order of 10 seconds and dozens of seconds to complete, respectively.

According to its marketing material, https://github.com/astral-sh/ruff can replace both of our linters and finish linting within a single second. If this is true, this would be a win-win, with one less dependency and shorter PR testing time.

We should probably investigate the consequences of switching to `ruff`.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #1155

This PR:

 - Adds a `ruff` configuration file.
 - Updates the related files to conform to the `ruff` style rules.

Found 1 bug (after 2000 lines changed 🥲):

https://github.com/Tribler/py-ipv8/blob/d52fb87890acbd24309872eedb39a0e5360cdbb4/ipv8/dht/routing.py#L194

`split()` can return `False`, causing this code to crash. Fixed in this PR.

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
validate

**Review by xoriole — APPROVED** [review]

**Pull request merged**
