### PR TITLE
Added default errbacks where appropriate

### LINKED ISSUE #383: Evaluate all addCallback calls
Even though IPv8 will keep on running, any `addCallback` (note: not `addCallbacks`) which doesn't get hooked up to an `errback` will produce an `uncaught error in Deferred`. Downstream projects (most notably Tribler) may fail on these uncaught errors.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #383

There were only a few cases (left) where `Deferred.addCallback` was used inappropriately. This PR fixes those.

### CODE REVIEW

**Comment by qstokkink** [comment]
Not quite sure what's wrong with the Python 3 checker.

**Comment by devos50** [comment]
I made some changes to `diff-cover` this weekend. Let me check.

**Comment by qstokkink** [comment]
👍

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@qstokkink fixed! 👍

**Comment by qstokkink** [comment]
@devos50 thanks

**Pull request merged**
