### PR TITLE
Added identity integration test isolation

### LINKED ISSUE #896: Isolate documentation integration tests
We have two documentation integration tests that use the wild network:

 - `doc/deprecated/attestation_tutorial_integration/`
 - `doc/basics/identity_tutorial_integration/`

These scripts work fine most of the time and were good enough for my personal use. However, as a formal PR check, they need to be more stable. REST API ports should be chosen more intelligently and the communities should be isolated.

For the deprecated tests, isolation currently happens with a hidden `git stash apply`, which is not very robust.

For the new identity REST endpoint [there exists a `X-Rendezvous` header for isolation](https://py-ipv8.readthedocs.io/en/latest/further-reading/advanced_identity/#setting-a-rendezvous-token), but it is unused in the test.

Both tests have `configuration['logger']['level'] = "ERROR"` (making debugging very annoying) and assign static ports for the REST API using `rest_manager.start(14410 + peer_id)`.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #896

This PR:

 - Adds a rendezvous token to the new identity integration test.
 - Adds a community isolation to the deprecated identity integration test.

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
Uhh.. `error: insufficient permission for adding an object to repository database .git/objects` and I also cannot wipe the workspace from Jenkins. I guess `root` has taken ownership of the directory or something?

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
Alright, that's all of the dumb stuff fixed. My apologies to everyone with notifications turned on: I'll be spamming "validate" a few times now.

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
6 runs without failure, seems OK.

**Review by egbertbouman — APPROVED** [review]

**Pull request merged**
