### PR TITLE
Various enhancements to attestation community

### PR DESCRIPTION
**Pull request by qstokkink**
Used for local staging and demo-ing

### CODE REVIEW

**Comment by devos50** [comment]
Great! I will review it in a moment. I prefer that the tunnel community stuff (#99) is reviewed + merged first since that is way less invasive than the single chain refactor.

**Comment by devos50** [comment]
@qstokkink want me to merge it? (or you can merge it yourself)

**Comment by qstokkink** [comment]
@devos50 sure 👍

**Comment by qstokkink** [comment]
@devos50 and yes, please merge it

**Comment by qstokkink** [comment]
@devos50 Thanks, I'll finish my write up for IDEMIA and then start on #99 .

**Pull request merged**
