### PR TITLE
Updated the version to 1.5.0

### LINKED ISSUE #414: Pip update for changed key
The overlay key is changed for the TrustchainTestNet overlay, this change should be reflected on pip

### PR DESCRIPTION
**Pull request by mitchellolsthoorn**
@qstokkink Can you update the pip package? The current version throws errors all over the place because of the invalid packet byte length

Closes #414

### CODE REVIEW

**Comment by mitchellolsthoorn** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
There have been quite a few changes since `1.4.1`, could you make it `1.5`?

**Comment by mitchellolsthoorn** [comment]
@qstokkink Done

**Comment by qstokkink** [comment]
Should be available on pip.

**Comment by mitchellolsthoorn** [comment]
Thx

**Pull request merged**
