### PR TITLE
Fixed tester scripts

### LINKED ISSUE #666: Test scripts broken after asyncio switch
Our Jenkins testers are now broken, see: https://github.com/Tribler/py-ipv8

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #666

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
Does anyone have remote access to the Mac tester? We need `nosetests3` installed.

**Comment by xoriole** [comment]
retest this please

**Comment by qstokkink** [comment]
Thanks!

**Pull request merged**
