### PR TITLE
Warn about long-running tasks in TaskManager

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by ichorid** [comment]
Well, pushing this into `master` means serious business... :dark_sunglasses:

**Comment by qstokkink** [comment]
Is this ready for review?

**Comment by qstokkink** [comment]
Please click here to learn more about IPv8's branch management:

[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=sqcLjcSloXs)

**Comment by egbertbouman** [comment]
@qstokkink Ready

**Pull request merged**
