### PR TITLE
Use python and nosetests versions explicitely

### PR DESCRIPTION
**Pull request by vandenheuvel**
I needed these changes to get this script working on Arch. @qstokkink will this break Ubuntu or Debian?

### CODE REVIEW

**Comment by qstokkink** [comment]
Ok to test

**Comment by qstokkink** [comment]
@vandenheuvel apparently, yes

**Comment by qstokkink** [comment]
If you add another case to the if for `nosetests2` and and change `python2.7` this PR should be good to go I think.

**Comment by vandenheuvel** [comment]
I'm currently searching on how to check the availability of a command. What do you think is the best way to do so?

**Comment by qstokkink** [comment]
You can use the line 10 format:
```bash
if nosetests --version >>/dev/null 2>&1; then
```

**Pull request merged**
