### PR TITLE
Updated Endpoint.close to be optionally async

### PR DESCRIPTION
**Pull request by egbertbouman**
This PR makes the necessary changes for `Endpoint.close` to be optionally async.

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
Alright, I think the killing of our build chain by dependabot has now been resolved. However, on to the next issue, our Windows testing machine seems to be offline (seemingly blocking everything else).

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by egbertbouman** [comment]
validate

**Review by qstokkink — APPROVED** [review]

**Pull request merged**
