### PR TITLE
Added auto PR review

### LINKED ISSUE #1100: Use secondary mechanism to approve PRs that are approved by `Tribler/core`
This issue is a different approach to core problem of #1091.

To reiterate: GitHub only sees PR approvals from users with write access as "real" approvals and the security model of this repository seeks to use as little write access as possible. This leads to the situation where nobody can offer formal PR approval, even though members of `Tribler/core` should be able to offer "real" approvals.

My new proposal is to use a secondary mechanism that:
 1. Listens for new approvals on a PR.
 2. Checks if the approving user is a member of `Tribler/core` and separately approves the PR as well.

To make this secondary approval valid/formal/"real" we can use the @tribler-ci account, the only account that will always have write access.

~~These are potential GitHub actions we could use for this: https://github.com/marketplace/actions/auto-approve, https://github.com/marketplace/actions/approve-pull-request~~ *EDIT: This approach failed.*

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #1100

This PR:

 - Adds a workflow to approve PRs that have been approved by `Tribler/core` members

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
@drew2a could you verify that I didn't do anything stupid? 😃

**Review by drew2a — APPROVED** [review]
🚀

**Comment by qstokkink** [comment]
Wait a second.. the review counts. Did GitHub change the triage permissions?
Perhaps this PR is no longer necessary.

**Pull request merged**
