### PR TITLE
Properly encoding to/from JSON in Python 3

### PR DESCRIPTION
**Pull request by devos50**
In this commit, I copied the json_util.py file over from Tribler. These methods are used in the IPv8 REST API to encode to/from JSON, in a Python 3-compatible way. I also fixed a few inconsistencies and code style errors.

### CODE REVIEW

**Comment by devos50** [comment]
My IDE is not complaining about the Pylint error for some reason, I think we can ignore it?

**Comment by ichorid** [comment]
Indeed, there *is* a pylint error, according to our pylint...

**Comment by qstokkink** [comment]
Also, please fix the Pylint error.

**Comment by qstokkink** [comment]
Third (and final?) thought, please move `json_util` to the `ipv8/REST` folder.

**Pull request merged**
