### PR TITLE
Test file consolidation and sanity fixes

### LINKED ISSUE #781: Not all tests inherit from TestBase
Some tests inherit from `asynctest.TestCase` instead of `TestBase`, this can result in the TestSuite looping forever upon programmer error. A search and replace of all `asynctest.TestCase` instances should resolve this and allow for programmers to make mistakes like this.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #781

This PR:

 - Makes sure all tests inherit from `TestBase` so the test suite correctly shuts down infinite loops and other failures.
 - Makes sure all overwrites of `setUp` call the `super.setUp`.
 - Doesn't lock up on `deliver_messages`.
 - Lets `run_all_tests` recover from a lock up.

### CODE REVIEW

**Comment by qstokkink** [comment]
I'm also going to resolve some more runtime warnings when running the coverage.

**Comment by qstokkink** [comment]
Found the first lockup:

```python
The test-suite locked up! Force quitting! Thread dump:
THREAD#139817595209536
|   File "create_test_coverage_report.py", line 54, in <module>
|       test_result = reporter.run(suite)
|   File "/usr/lib/python3.8/unittest/runner.py", line 176, in run
|       test(result)
|   File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
|       return self.run(*args, **kwds)
|   File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
|       test(result)
|   File "/usr/lib/python3.8/unittest/suite.py", line 84, in __call__
|       return self.run(*args, **kwds)
|   File "/usr/lib/python3.8/unittest/suite.py", line 122, in run
|       test(result)
|   File "/usr/lib/python3.8/unittest/case.py", line 736, in __call__
|       return self.run(*args, **kwds)
|   File "/home/quinten/.local/lib/python3.8/site-packages/asynctest/case.py", line 297, in run
|       self._run_test_method(testMethod)
|   File "/home/quinten/.local/lib/python3.8/site-packages/asynctest/case.py", line 354, in _run_test_method
|       self.loop.run_until_complete(result)
|   File "/home/quinten/.local/lib/python3.8/site-packages/asynctest/case.py", line 224, in wrapper
|       return method(*args, **kwargs)
|   File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
|       self.run_forever()
|   File "/home/quinten/.local/lib/python3.8/site-packages/asynctest/case.py", line 224, in wrapper
|       return method(*args, **kwargs)
|   File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
|       self._run_once()
|   File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
|       event_list = self._selector.select(timeout)
|   File "/home/quinten/.local/lib/python3.8/site-packages/asynctest/selector.py", line 299, in select
|       return self._selector.select(timeout)
|   File "/usr/lib/python3.8/selectors.py", line 468, in select
|       fd_event_list = self._selector.poll(timeout, max_ev)
Pending tasks:
>     <Task pending name='AttestationCommunity:_check_tasks' coro=<interval_runner() running at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:15> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f29cf5a5d90>()]> cb=[TaskManager.register_task.<locals>.done_cb() at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:127]>
>     <Task pending name='AttestationCommunity:_check_tasks' coro=<interval_runner() running at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:15> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f29cf5af1f0>()]> cb=[TaskManager.register_task.<locals>.done_cb() at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:127]>
>     <Task pending name='RequestCache:_check_tasks' coro=<interval_runner() running at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:15> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f29cf5a55b0>()]> cb=[TaskManager.register_task.<locals>.done_cb() at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:127]>
>     <Task pending name='RequestCache:_check_tasks' coro=<interval_runner() running at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:15> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f29cf444fa0>()]> cb=[TaskManager.register_task.<locals>.done_cb() at /home/quinten/Documents/py-ipv8/ipv8/taskmanager.py:127]>
>     <Task pending name='Task-4038' coro=<TestCommunity.test_verify_attestation_range() running at /home/quinten/Documents/py-ipv8/ipv8/test/attestation/wallet/test_attestation_community.py:327> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f29cf367700>()]> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]>
```

**Comment by qstokkink** [comment]
I'm guessing `deliver_messages` counts the `_check_tasks` internal loop of the TaskManager as separate tasks and doesn't ever finish.

**Comment by qstokkink** [comment]
Last warning is this one:

```python
/home/quinten/.local/lib/python3.8/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name Transaction. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
```

But I'm not quite sure where `Transaction` is specified.

**Comment by qstokkink** [comment]
Next issue: `python3 run_all_tests.py` doesn't recover from a `while True` loop in a unit test.

**Comment by qstokkink** [comment]
Now I can actually see the error. It seems `ipv8.test.REST.attestationendpoint.test_attestation_endpoint.TestAttestationEndpoint.test_get_verification_output` is locking up.

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
Wait, did you just speed up the test duration by almost three times?!

```
[SUCCESS] Ran 560 tests in 7.06 seconds (53.96 seconds total in tests).
```

**Comment by qstokkink** [comment]
Uhh.. yes?

Though I'm not quite sure how.

**Comment by devos50** [comment]
I think it is because they now all inherit from `TestBase`?

**Comment by qstokkink** [comment]
🤷 

At least the tests are faster now, IPv8 was suffering from sluggish tests 😄

**Comment by qstokkink** [comment]
Ooooooh waaaaait. The speedup actually makes sense. It was needlessly waiting for the periodic task check before.

**Pull request merged**
