### PR TITLE
Ported several more classes to Python 3

### PR DESCRIPTION
**Pull request by qstokkink**
Related to #265.

### CODE REVIEW

**Comment by devos50** [comment]
Why is there no pylint?

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
Too many other PRs have been tested between PR submission and your review.

**Comment by devos50** [comment]
Ah, so I'm too slow 😆

**Comment by qstokkink** [comment]
@devos50 confirmed by github 👍

**Pull request merged**
