### PR TITLE
ON HOLD: Twistify creation of circuits

### PR DESCRIPTION
**Pull request by devos50**
In this PR, I twistified the creation of circuits. This cleans up the test code a bit.

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
Can this be merged?

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
@qstokkink the on hold label looks very depressing :(

**Comment by qstokkink** [comment]
It's been almost a year since this was opened. Is this PR `on hold` or just `dead`?

**Comment by devos50** [comment]
I think it's dead :(

**Pull request closed without merging**
