### PR TITLE
ON HOLD: Gossip overlay

### PR DESCRIPTION
**Pull request by qstokkink**
Primitive for gossip.

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by ichorid** [comment]
So, what does it do? What's a general idea? What functionality does it implement?

**Comment by qstokkink** [comment]
@ichorid this is an implementation of https://github.com/Tribler/tribler/issues/3690 . If it will work and how we should test this, I have no idea.

**Pull request closed without merging**
