### PR TITLE
Fixed typing issues

### PR DESCRIPTION
**Pull request by egbertbouman**
This PR fixes https://github.com/Tribler/py-ipv8/issues/1262.

### CODE REVIEW

**Comment by egbertbouman** [comment]
validate

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Review by qstokkink — APPROVED** [review]

**Pull request merged**
