### PR TITLE
Added tracker_reporter_plugin script to collect anonymized tracker statistics

### PR DESCRIPTION
**Pull request by kozlovsky**
This PR adds the possibility to collect anonymized statistics from bootstrap nodes.
To keep changes in the IPv8 code minimal, I put all additional logic to manage HyperLogLog counters into a separate repo.
IPv8 tracker imports code from `trackermetricsreporter`, and if this module was not installed continues to work as before.

### CODE REVIEW

**Review by qstokkink — CHANGES_REQUESTED** [review]
I like what you changed, but not where the changes are located.

Your extension offers a distinct change in focus from the base tracker script, which I believe is a valuable addition. At the same time, I don't want to lose the focus of the base tracker script itself. Therefore, I request the following change:

I request you to upgrade your script to its own file (something like `tracker_reporter_plugin.py`), subclassing the existing `EndpointServer`. This allows IPv8 to maintain both (1) a focused tracker script aimed at probing network health and (2) a tracker script aimed to be performant (the current `tracker_plugin.py`). As an added bonus to this focus, the `from trackermetricsreporter import MetricsReporter` can then be a hard import instead of an optional import.

**Comment by kozlovsky** [comment]
I refactored the code and extract the common classes to `ipv8.tracker_service` (is it a good name?)

The changes are split into three different commits, you can look at the second commit to see what I changed to make classes extensible (is `on_peer_introduction_request` a suitable hook name?).

I'm not totally sure I'm right about calling `reporter.shutdown` at the end of extracted async method `ReportingTrackerService.shutdown` in the third commit. `reporter.shutdown` calls `Thread.join()` internally and it can block `ReportingTrackerService.shutdown` method execution for about a second, and it does not look ideal inside the async event loop.

**Review by qstokkink — CHANGES_REQUESTED** [review]
Good improvement, thanks for the changes. 👍 

I have 2 concerns remaining:

 1. Regarding:
 > I refactored the code and extract the common classes to `ipv8.tracker_service` (is it a good name?)

 I like the file name and the common functionality in the same file. However, the `/ipv8/` folder is for the core library classes, not for script support classes. Please place this script functionality in the `/scripts/` folder.
As an added bonus you can shed some code from the `tracker_plugin.py` and `tracker_reporting_plugin.py` by **only** performing the `__scriptpath__` import in this `tracker_service.py` file, after making the change.

 2. This is not so much to do with the changes itself, but more the form of the PR: please take note of point 5 of https://github.com/Tribler/py-ipv8/blob/master/CONTRIBUTING.md#i-want-to-open-a-pull-request
  If you don't stick to this naming outlined in `CONTRIBUTING.md`, I have to manually correct the release notes for each IPv8 release.

**Comment by qstokkink** [comment]
add to whitelist

**Review by qstokkink — CHANGES_REQUESTED** [review]
Looking good, almost there. Just some style issues left.

Regarding the style issues: some cannot be fixed. I'll outline what needs fixing and what can be ignored.

**Pylint**
*scripts/tracker_reporter_plugin.py*
 - ~10: E0401: (import-error), : Unable to import 'trackermetricsreporter'~
 - 34: W0613: (unused-argument), main: Unused argument 'argv'
 - 36: C0301: (line-too-long), : Line too long (121/120)

*scripts/tracker_service.py*
 - ~16: W0611: (unused-import), : Unused import __scriptpath__~
 - 54: R1725: (super-with-arguments), EndpointServer.__init__: Consider using Python 3 style super() without arguments
 - ~69: W0703: (broad-except), EndpointServer.on_packet: Catching too general exception Exception~
 - 70: C0415: (import-outside-toplevel), EndpointServer.on_packet: Import outside toplevel (traceback)
 - ~74: W0612: (unused-variable), EndpointServer.on_generic_introduction_request: Unused variable 'dist'~
 - 86: C0325: (superfluous-parens), : Unnecessary parens after 'not' keyword
 - 101: W0107: (unnecessary-pass), EndpointServer.on_peer_introduction_request: Unnecessary pass statement
 - 112: R0205: (useless-object-inheritance), TrackerService: Class 'TrackerService' inherits from object, can be safely removed from bases in python3
 - 129: W0201: (attribute-defined-outside-init), TrackerService.start_tracker: Attribute 'listen_port' defined outside __init__
 
**Flake8**
*scripts/tracker_service.py*
 - ~135: T001: print found.~
 - ~145: T001: print found.~

*scripts/tracker_reporter_plugin.py*
 - ~12: I100: Import statements are in the wrong order. 'from tracker_service import EndpointServer, TrackerService' should be before 'from trackermetricsreporter import MetricsReporter' and in a different group.~

**Comment by kozlovsky** [comment]
I updated the code to satisfy the linter

**Review by qstokkink — APPROVED** [review]
Thanks for sticking with us, looks good. 👍

**Pull request merged**
