### PR TITLE
Aesthetic changes and testing (documentation) updates

### PR DESCRIPTION
**Pull request by qstokkink**
This PR includes:

 - Changed the color of logged output to "Bright Blue".
 - Show the time for each individual test in milliseconds.
 - Removal of old testing scripts (no more `test_classes_list.txt`).
 - Updated documentation for testing (and Python 3 execution).

### CODE REVIEW

**Comment by qstokkink** [comment]
Seems like everything is failing correctly.

I am second-guessing my choice of yellow for the logging output though. @devos50 @egbertbouman any suggestions for a less eye-popping color? Blue or purple maybe?

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
Here are the color options side by side:

afbeelding

My personal preference is bright blue.

**Comment by egbertbouman** [comment]
@qstokkink I agree. Bright blue seems like the most readable.

**Comment by qstokkink** [comment]
Thanks for your vote, that's 3/3 for Bright Blue so far.

**Comment by qstokkink** [comment]
Ready for review: be sure to check out the test runner output (for example https://jenkins-ci.tribler.org/job/ipv8/job/test_ipv8_PR_unittests_linux/1681/).

**Comment by qstokkink** [comment]
I'll also remove the old scripts and change the documentation in this PR.

**Comment by qstokkink** [comment]
Ready for review. I am going to miss the old Windows batch script though.

**Pull request merged**
