### PR TITLE
Added support for Futures to the TaskManager

### PR DESCRIPTION
**Pull request by egbertbouman**
This PR does the following:
* Adds support for `Futures` to the `TaskManager`
* Adds `TaskManager.register_executor_task` that allows for non-async functions to be scheduled on the threadpool. It's important to note while `TasksManager.shutdown` will cancel the future itself, it won't actually stop the task (unless you manually add support for this, for example, by passing an event).

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by egbertbouman** [comment]
validate

**Review by qstokkink — CHANGES_REQUESTED** [review]
Your Christmas tree is failing: https://github.com/Tribler/py-ipv8/actions/runs/7503153590

**Review by qstokkink — APPROVED** [review]

**Comment by egbertbouman** [comment]
I forgot that I had to check the GH actions as well. I agree that it would be nice to have this added to the PR checks. Anyway, the Christmas tree is nice and green now.

**Comment by qstokkink** [comment]
🎅 So be it, let there be Christmas trees. Issue created.

**Pull request merged**
