### PR TITLE
Added swagger docs

### PR DESCRIPTION
**Pull request by egbertbouman**
Adds swagger docs to /docs:

image

### CODE REVIEW

**Comment by egbertbouman** [comment]
retest this please

**Comment by qstokkink** [comment]
Cool, seems to resolve #390.

**Comment by qstokkink** [comment]
You can ignore the Windows error.

**Comment by egbertbouman** [comment]
@qstokkink Will do. The error on Linux is due to the REST tests running in parallel. I'll try to fix that one.

**Comment by qstokkink** [comment]
Addressed the Windows error in #613.

**Comment by qstokkink** [comment]
Merged, the Window test should pass when you rebase.

**Comment by qstokkink** [comment]
Wait. Are the file changes correct?

**Pull request merged**
