### PR TITLE
Fixed tunnel endpoints

### PR DESCRIPTION
**Pull request by egbertbouman**
This PR fixes a number of issues with the tunnel endpoint:
* Fixes an issue with the tunnel settings endpoint raising an exception. Since I also wanted to return the `CommunitySettings` defaults, I had to resort to using `dir`.
* Fixes an issue with the relays missing a direction field.
* Fixes an issue with incorrect swagger docs for the speedtest endpoint.

### CODE REVIEW

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Review by qstokkink — APPROVED** [review]

**Pull request merged**
