### PR TITLE
ON HOLD: Refactor reactor.callLater usage into TaskManager Clock

### LINKED ISSUE #330: Refactor reactor.callLater usage
Right now we allow programmers to use Twisted's `reactor.callLater` directly. As pointed out before (by @ichorid) this blocks the reactor (ex. `select()` or `poll()`) for a certain time period, before the reactor figures out that a call was cancelled. This especially hurts the `DHTCommunity` tests.

What we should do is move all of the `reactor.callLater` calls to a `Clock` object which we can advance manually. We already do this for the `TestTaskManager` tests. We can then manually advance time using the `Clock` object using (what should be) the only measure of time in `IPv8` instances: `IPv8.on_tick()`. The usage can be sketched as follows:

afbeelding

One downside to this approach is that we get coarser time granularity for callbacks and thus batching of calls. If programmers ever start massively scheduling `callLater` calls we will see CPU spikes. Right now this is not the case, we mostly use proper `Deferred` callback chains.
Another downside is that we will now need to pass `Clock` instances to all `TaskManager`s. We _cannot_ make this a singleton as this would violate the ability for `IPv8` instances to coexist in the same interpreter.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #330

 - [X] Expose `TaskManager._reactor`.
 - [x] Pass instance of `Clock` into all `TaskManager` subclasses.
 - [x] Time management in `IPv8` instances.

### CODE REVIEW

**Comment by qstokkink** [comment]
Bad news, even with `Clock` the DHT tests are slow:

```
THREAD#139824782624512
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#139824791017216
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#139825153349440
|   File "/home/quinten/Downloads/pycharm-community-2018.2/helpers/pycharm/_jb_nosetest_runner.py", line 17, in <module>
|       nose.main(addplugins=[TeamcityReport()])
|   File "/usr/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__
|       **extra_args)
|   File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
|       self.runTests()
|   File "/usr/lib/python2.7/dist-packages/nose/core.py", line 207, in runTests
|       result = self.testRunner.run(self.test)
|   File "/usr/lib/python2.7/dist-packages/nose/core.py", line 62, in run
|       test(result)
|   File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 177, in __call__
|       return self.run(*arg, **kw)
|   File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 224, in run
|       test(orig)
|   File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 177, in __call__
|       return self.run(*arg, **kw)
|   File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 224, in run
|       test(orig)
|   File "/usr/lib/python2.7/dist-packages/nose/case.py", line 45, in __call__
|       return self.run(*arg, **kwarg)
|   File "/usr/lib/python2.7/dist-packages/nose/case.py", line 133, in run
|       self.runTest(result)
|   File "/usr/lib/python2.7/dist-packages/nose/case.py", line 151, in runTest
|       test(result)
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 119, in __call__
|       return self.run(*args, **kwargs)
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 1043, in run
|       _collectWarnings(self._warnings.append, self._runFixturesAndTest, result)
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 181, in _collectWarnings
|       result = f(*args, **kwargs)
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 303, in _runFixturesAndTest
|       self._classCleanUp(result)
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 226, in _classCleanUp
|       util._Janitor(self, result).postClassCleanup()
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/util.py", line 117, in postClassCleanup
|       self._cleanThreads()
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/util.py", line 163, in _cleanThreads
|       reactor._stopThreadPool()
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1047, in _stopThreadPool
|       self.threadpool.stop()
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 280, in stop
|       thread.join()
|   File "/usr/lib/python2.7/threading.py", line 940, in join
|       self.__block.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#139825031661312
|   File "/usr/lib/python2.7/threading.py", line 778, in __bootstrap
|       raise
|   File "/usr/lib/python2.7/threading.py", line 855, in __bootstrap_inner
|       pass
|   File "/usr/lib/python2.7/threading.py", line 758, in run
|       del self.__target, self.__args, self.__kwargs
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
|       task()
|   File "/usr/lib/python2.7/Queue.py", line 182, in get
|       self.not_empty.release()
|   File "/usr/lib/python2.7/threading.py", line 371, in wait
|       self._acquire_restore(saved_state)
THREAD#139824799409920
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 848, in __bootstrap_inner
|       with _active_limbo_lock:
|   File "/usr/lib/python2.7/threading.py", line 758, in run
|       del self.__target, self.__args, self.__kwargs
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
|       task()
|   File "/usr/lib/python2.7/Queue.py", line 182, in get
|       self.not_empty.release()
|   File "/usr/lib/python2.7/threading.py", line 371, in wait
|       self._acquire_restore(saved_state)
THREAD#139824807802624
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 848, in __bootstrap_inner
|       with _active_limbo_lock:
|   File "/usr/lib/python2.7/threading.py", line 758, in run
|       del self.__target, self.__args, self.__kwargs
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
|       task()
|   File "/usr/lib/python2.7/Queue.py", line 182, in get
|       self.not_empty.release()
|   File "/usr/lib/python2.7/threading.py", line 371, in wait
|       self._acquire_restore(saved_state)
THREAD#139825023268608
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 848, in __bootstrap_inner
|       with _active_limbo_lock:
|   File "/usr/lib/python2.7/threading.py", line 758, in run
|       del self.__target, self.__args, self.__kwargs
|   File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
|       task()
|   File "/usr/lib/python2.7/Queue.py", line 182, in get
|       self.not_empty.release()
|   File "/usr/lib/python2.7/threading.py", line 371, in wait
|       self._acquire_restore(saved_state)
```

**Comment by qstokkink** [comment]
Oh god, Twisted trial uses a `reactor.callLater` internally for its timeout per test method.

When I set the `twisted.trial.util.DEFAULT_TIMEOUT_DURATION` to a lower value, the tests finish faster.

**Comment by ichorid** [comment]
related https://github.com/Tribler/py-ipv8/pull/245#issuecomment-418434274

**Comment by qstokkink** [comment]
Putting this on hold, not sure if we want it.

**Pull request closed without merging**
