### PR TITLE
Added backwards compatibility for Discovery intro

### LINKED ISSUE #80: Strange message from Tribler
In Tribler someone is sending the following message:

```
STRUCT            DATA                       DESCRIPTION
====================================================================
DISPERSY_VERSION  00                         0
COMMUNITY_VERSION 02                         2
COMMUNITY_ID      7e 31 36 85 | c1 91 2a 14
                  12 79 f8 24 | 8f c8 db 58
                  99 c5 df 5a                DiscoveryCommunity
MESSAGE_ID        f6                         IntroductionRequest
GLOBAL_TIME       00 00 00 00 | 00 00 00 e5  229
DESTINATION       59 3d 0b 80 | 53 c7        (89.61.11.128, 21447)
LAN               ed c3 04 f2 | 20 37        (237.195.4.242, 8247)
WAN               97 ff ed 0c | 74 99        (151.255.237.12, 29849)
FLAGS             67                         (connection_type_0=0,
                                              connection_type_1=1,
                                              dflag0=1,
                                              dflag1=0,
                                              dflag2=0,
                                              tunnel=1,
                                              sync=1,
                                              advice=1)
IDENTIFIER        32 f3                      13043
TIME_LOW          91 5e 7f f5 | ce 13 c0 a8  10474950477011468456
TIME_HIGH         01 71 1e 4f | bc cc c3 82  103897594225017730
MODULO            1e 4f                      7759
OFFSET            01 84                      388
FUNCTIONS         9c                         10011100
BLOOMFILTER_SIZE  <N/A>                      MISSING!
BLOOMFILTER       <N/A>                      MISSING!
```

The contents seem like garbage, but this message has been correctly signed though.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #80

### CODE REVIEW

**Comment by qstokkink** [comment]
@xoriole or @devos50 could one of you review?

**Comment by qstokkink** [comment]
@devos50 done

**Comment by devos50** [comment]
@qstokkink thanks!

**Comment by qstokkink** [comment]
With this we finally get rid of the `QQHHBH` stuff in the terminal.

**Pull request merged**
