### PR TITLE
Updated TunnelCommunity cell logic

### PR DESCRIPTION
**Pull request by egbertbouman**
The sole purpose of this PR is to allow part of the `TunnelCommunity` to be moved to Rust (https://github.com/Tribler/py-ipv8/issues/1119). It moves much of the crypto related logic to `crypto.py` and exit logic to `exit_socket.py`. These two files combined will be the Python fallback for the future `RustEndpoint`.

The en/decryption of `CellPayloads` is moved out of the `TunnelCommunity`, and is now located in a wrapper around `Endpoint` called `CryptoEndpoint`. The `CryptoEndpoint` is responsible for sending/receiving/relaying `CellPayloads`, and is also used for storing the routing objects. The construction of these routing objects, however, remains in the `TunnelCommunity`. This way we can keep the tunnel control logic in Python, but move the actual crypto to Rust.

I've also moved all the information required to process/forward `CellPayloads` to `Hop` objects. This class already existed before, but now `RelayRoute`/`ExitSocket` objects have a single `Hop` object as well. This simplifies crypto operations to a simple loop that iterates over one or more `Hop` instances.

Finally, I've increased the traffic limit to 10GB, since the current limit of 250MB can (with Rust) be reached in seconds.

### CODE REVIEW

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Pull request merged**
